// Copyright (C) 2026 Nucleic Logic Studios, LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
// Bundled content from tools/create-ai-tool � regenerated by bundling the source files.
// To update: edit the source in tools/create-ai-tool/ then re-run the bundle step.

export const SKILL_MD = `---
name: create-ai-tool
description: >-
  Use this skill when asked to create, package, or publish a reusable AI tool for
  the aitools registry � even if the user doesn't explicitly say "registry" or
  "aitools". Covers all four package types: skill (SKILL.md workflow instructions),
  subagent (agent persona files), prompt (reusable templates), and mcp-tool (MCP
  server registrations). Also use when bumping a version or republishing an
  existing package.
metadata:
  author: ai-tools
---

Every package needs a folder with \`aitools.manifest.json\` + at least one content file.

## Creating a package

### Step 1: Create the folder and content file

For a **skill** � create \`SKILL.md\` with required YAML frontmatter:

\`\`\`markdown
---
name: my-skill
description: >-
  Use this skill when [user intent]. Also use when [indirect trigger, even if
  user doesn't say the domain name explicitly].
---

[Step-by-step agent instructions here]
\`\`\`

The \`name\` value **must exactly match the folder name**. This is how agents discover the skill � a mismatch causes it to never activate.

VS Code and Cursor support additional optional frontmatter fields beyond the base spec. Read [references/platform-paths.md](references/platform-paths.md#platform-specific-skillmd-frontmatter-fields) if the user needs:
- \`disable-model-invocation: true\` � slash-command-only, never auto-loads (VS Code + Cursor)
- \`user-invocable: false\` � hide from \`/\` menu but keep auto-loading (VS Code only)
- \`argument-hint\` � hint shown in chat input when invoked as \`/skill-name\` (VS Code only)

For a **subagent** � create a \`.md\` file with YAML frontmatter (name, description, tools list) and sections for Role, Responsibilities, Rules, Output Format.

For a **prompt** � create a \`.md\` file with the reusable instruction or template.

For an **mcp-tool** � the manifest needs an \`mcpServer\` block. Content files are optional. Read [references/manifest-reference.md](references/manifest-reference.md) for the \`mcpServer\` field spec.

### Step 2: Initialise the manifest

\`\`\`bash
cd my-skill/
aitools manifest init          # interactive � prompts for all fields
\`\`\`

Non-interactive (CI / scripted):

\`\`\`bash
aitools manifest init --yes \\
  --name "my-skill" \\
  --category skill \\
  --description "One-line summary shown in search results"
\`\`\`

### Step 3: Validate

\`\`\`bash
aitools manifest validate
\`\`\`

Fix every reported error before continuing. Most common:
- \`name\` must be lowercase, hyphens only, no leading/trailing hyphen
- \`src\` file doesn't exist on disk
- \`dest\` accidentally prefixed with the category dir (don't � the installer adds it)

### Step 4: Dry-run, then publish

\`\`\`bash
aitools publish --dry-run   # confirm files list
aitools publish             # upload to registry
\`\`\`

### Bumping a version

\`\`\`bash
aitools manifest bump patch   # 1.0.0 ? 1.0.1
aitools manifest bump minor   # 1.0.0 ? 1.1.0
aitools manifest bump major   # 1.0.0 ? 2.0.0
\`\`\`

Then publish again: \`aitools publish\`.

---

## \`dest\` path rule

\`dest\` is appended to the category install directory. Never repeat the category dir:

- ? \`"dest": "my-skill/SKILL.md"\` ? \`.agents/skills/my-skill/SKILL.md\`
- ? \`"dest": "skills/my-skill/SKILL.md"\` � double-prefixed, wrong

Add \`"template": true\` to a file entry to enable Handlebars \`{{variable}}\` substitution during install.

---

## Writing a good \`description\` for a skill

The description is the **only** signal agents use to decide whether to activate the skill. Write it as an instruction:

- **Imperative**: "Use this skill when�" not "This skill does�"
- **Cover indirect triggers**: mention what the user is trying to achieve, not just the domain name � "even if they don't explicitly say 'registry'"
- **Be specific**: list the concrete operations the skill covers
- **Hard limit**: 1024 characters

Before: \`"Create and publish tools."\` � too vague, won't activate.

After: \`"Use this skill when asked to create, package, or publish a reusable AI tool � even if the user doesn't say 'registry'. Covers skills, subagents, prompts, and MCP tools."\` � activates on intent.

---

## Gotchas

- **\`name\` in \`SKILL.md\` frontmatter must match the folder name.** Mismatches silently break discovery.
- **\`repository\` in the manifest must be a full URL.** \`user/repo\` fails validation � use \`https://github.com/user/repo\`.
- **Run \`manifest validate\` before every publish** � catches missing files before they reach the registry.
- **\`dest\` is relative to the category dir, not the project root.** Do not prefix it with \`skills/\`, \`agents/\`, etc.

---

## References

Read [references/manifest-reference.md](references/manifest-reference.md) for the full \`aitools.manifest.json\` field reference, including the \`mcpServer\` block and all optional fields.

Read [references/platform-paths.md](references/platform-paths.md) if you need to know exactly where files land per platform (vscode, claude, cursor, windsurf, universal) � useful when writing \`dest\` values or advising users on where tools install.
`;

export const MANIFEST_REFERENCE_MD = `# aitools.manifest.json � Full Field Reference

## Required fields

| Field | Type | Rules |
|---|---|---|
| \`name\` | string | npm-style: lowercase, hyphens, numbers. Scoped (\`@scope/name\`) allowed. |
| \`version\` | string | Semver: \`1.0.0\`, \`1.0.0-beta.1\`, \`1.0.0+build.1\` |
| \`description\` | string | One-liner shown in registry search results. Non-empty. |
| \`category\` | enum | \`skill\` \\| \`subagent\` \\| \`prompt\` \\| \`mcp-tool\` |
| \`files\` | array | At least one entry. See File entries below. |

## Optional fields

| Field | Type | Notes |
|---|---|---|
| \`author\` | string | Free-form author name or email |
| \`repository\` | string (URL) | Must be a full URL � \`https://github.com/user/repo\`, not \`user/repo\` |
| \`keywords\` | string[] | Freeform search terms shown in registry |
| \`tags\` | string[] | Metadata for AI discovery / smart-find |
| \`dependencies\` | Record\\<string, string\\> | Other AITools packages required. Key = package name, value = semver range |
| \`mcpServer\` | object | Required when \`category\` is \`mcp-tool\`. See mcpServer block below. |

## File entries (\`files[]\`)

\`\`\`jsonc
{
  "src": "SKILL.md",            // path relative to the manifest file
  "dest": "my-skill/SKILL.md",  // path relative to the category install dir
  "template": true              // optional � enables Handlebars {{variable}} substitution
}
\`\`\`

\`dest\` rule: the installer prepends the category directory automatically.
- ? \`"dest": "my-skill/SKILL.md"\` ? \`.agents/skills/my-skill/SKILL.md\`
- ? \`"dest": "skills/my-skill/SKILL.md"\` � do not repeat the category dir

## \`mcpServer\` block

Used only when \`category\` is \`"mcp-tool"\`.

\`\`\`jsonc
{
  "command": "node",              // executable (local servers)
  "args": ["server.js"],         // arguments
  "env": {                       // environment variables
    "DB_URL": "\${env:DB_URL}"
  },
  "url": "https://�/mcp",        // remote HTTP server (overrides command)
  "type": "stdio"                // "stdio" (default) | "http"
}
\`\`\`

For a local stdio server:
\`\`\`json
{
  "mcpServer": {
    "command": "node",
    "args": ["server.js"],
    "type": "stdio"
  }
}
\`\`\`

For a remote HTTP server (no files needed):
\`\`\`json
{
  "mcpServer": {
    "url": "https://my-mcp-server.example.com/mcp",
    "type": "http"
  },
  "files": []
}
\`\`\`

## Full example � skill

\`\`\`json
{
  "name": "@acme/jest-tdd",
  "version": "1.0.0",
  "description": "TDD workflow for Jest + ts-jest projects",
  "category": "skill",
  "files": [
    { "src": "SKILL.md", "dest": "jest-tdd/SKILL.md" }
  ],
  "author": "Acme Corp",
  "repository": "https://github.com/acme/jest-tdd-skill",
  "keywords": ["testing", "jest", "tdd"],
  "tags": ["typescript", "testing"]
}
\`\`\`

## Full example � mcp-tool

\`\`\`json
{
  "name": "@acme/postgres-mcp",
  "version": "1.0.0",
  "description": "MCP server for PostgreSQL � run queries, inspect schema",
  "category": "mcp-tool",
  "mcpServer": {
    "command": "node",
    "args": ["server.js"],
    "env": { "DATABASE_URL": "\${env:DATABASE_URL}" },
    "type": "stdio"
  },
  "files": [
    { "src": "server.js", "dest": "server.js" }
  ],
  "tags": ["database", "postgresql"]
}
\`\`\`
`;

export const PLATFORM_PATHS_MD = `# Platform Reference

## Install paths

The \`dest\` in the manifest is appended to the category directory shown below.

## Project scope

| Platform | skill | subagent | prompt | mcp config |
|---|---|---|---|---|
| **universal** | \`.agents/skills/\` | \`.agents/agents/\` | \`.agents/prompts/\` | � |
| **vscode** | \`.agents/skills/\` | \`.github/agents/\` | \`.agents/prompts/\` | \`.vscode/mcp.json\` |
| **cursor** | \`.agents/skills/\` | \`.agents/agents/\` | \`.agents/prompts/\` | \`.cursor/mcp.json\` |
| **windsurf** | \`.agents/skills/\` | \`.agents/agents/\` | \`.agents/prompts/\` | \`.windsurf/mcp.json\` |
| **claude** | \`.claude/skills/\` | \`.claude/agents/\` | \`.claude/commands/\` | \`.mcp.json\` |

## User scope (global)

| Platform | skill | subagent | prompt | mcp config |
|---|---|---|---|---|
| **vscode** | \`~/.copilot/skills/\` | \`~/.copilot/agents/\` | \`~/.copilot/prompts/\` | \`~/.vscode/mcp.json\` |
| **cursor** | \`~/.agents/skills/\` | \`~/.agents/agents/\` | \`~/.agents/prompts/\` | \`~/.cursor/mcp.json\` |
| **claude** | \`~/.claude/skills/\` | \`~/.claude/agents/\` | \`~/.claude/commands/\` | \`~/.claude/mcp.json\` |

## Example

A skill manifest with \`"dest": "jest-tdd/SKILL.md"\` installs to:

| Platform | Project scope result |
|---|---|
| universal / vscode / cursor | \`.agents/skills/jest-tdd/SKILL.md\` |
| claude | \`.claude/skills/jest-tdd/SKILL.md\` |

## Designing \`dest\` values

- Use a subdirectory matching the package name so skills don't collide: \`"dest": "my-skill/SKILL.md"\` not \`"dest": "SKILL.md"\`.
- For skills, the folder name in \`dest\` **must match the \`name\` field in the \`SKILL.md\` frontmatter** � that's how agents find the skill file.
- For subagents and prompts, a flat \`"dest": "my-agent.md"\` is fine if only one file is shipped.

---

## Platform-specific SKILL.md frontmatter fields

Beyond the base [agentskills.io spec](https://agentskills.io/specification) (\`name\`, \`description\`, \`license\`, \`compatibility\`, \`metadata\`, \`allowed-tools\`), VS Code and Cursor support additional frontmatter fields.

### \`disable-model-invocation\`

**Supported by**: VS Code, Cursor

When \`true\`, the skill is never auto-loaded by the agent based on context. It only activates when the user explicitly types \`/skill-name\` in chat. Use this for skills that should be on-demand slash commands rather than auto-triggered.

\`\`\`yaml
---
name: my-skill
description: �
disable-model-invocation: true
---
\`\`\`

Default: \`false\` (agent auto-loads when relevant).

### \`user-invocable\`

**Supported by**: VS Code only

Controls whether the skill appears in the \`/\` slash command menu in chat. Defaults to \`true\`.

Set to \`false\` to hide the skill from the \`/\` menu while still allowing the agent to load it automatically based on context. Useful for background knowledge skills you don't want cluttering the slash command list.

\`\`\`yaml
---
name: my-skill
description: �
user-invocable: false
---
\`\`\`

| \`user-invocable\` | \`disable-model-invocation\` | Slash menu | Auto-load |
|---|---|---|---|
| \`true\` (default) | \`false\` (default) | ? | ? |
| \`false\` | \`false\` | ? | ? |
| \`true\` | \`true\` | ? | ? |
| \`false\` | \`true\` | ? | ? (disabled) |

### \`argument-hint\`

**Supported by**: VS Code only

Hint text shown in the chat input field when the skill is invoked as a slash command. Helps the user know what additional context to provide.

\`\`\`yaml
---
name: run-tests
description: �
argument-hint: "[test file] [--watch]"
---
\`\`\`

The hint appears as placeholder text after \`/run-tests\` in the chat input.

`;
